#!/usr/bin/env bash
# Fetch the experiment substrate v2: Apache Guacamole manual, multiple chapters.
#
# v1 pulled only the architecture chapter. That chapter is ~700 words, contains zero
# data stores, and yields roughly a dozen elements. Every run would have scored near
# full coverage and the experiment would have returned a null result by construction:
# a ceiling effect, not a finding.
#
# v2 widens the substrate so the STRIDE grid actually has data stores, secrets at rest,
# and more than one trust boundary to lose.
#
# The substrate is fetched, never authored. Anyone re-running this pulls the same bytes
# and can check the hash.
#
# Requires: curl, pandoc

set -euo pipefail

VERSION="1.5.5"
BASE="https://guacamole.apache.org/doc/${VERSION}/gug"

# Core set. Each adds elements the architecture chapter lacks.
#   guacamole-architecture  - the DFD spine: browser, client, web app, guacd, plugins, libguac
#   configuring-guacamole   - GUACAMOLE_HOME, guacamole.properties, user-mapping.xml,
#                             guacd host/port, the unencrypted-by-default webapp->guacd hop,
#                             connection parameters holding remote credentials
#   jdbc-auth               - the database: users, permissions, stored connection secrets
#   reverse-proxy           - the proxy boundary in front of the web app
#
# Optional, adds a sensitive data store. Uncomment if you want a wider grid and are
# willing to spend longer on ground truth.
#   recording-playback      - session recordings written to disk
CHAPTERS=(
  guacamole-architecture
  configuring-guacamole
  jdbc-auth
  reverse-proxy
  # recording-playback
)

mkdir -p prompts truth runs .fetch

echo "Fetching ${#CHAPTERS[@]} chapters from ${BASE}"

for ch in "${CHAPTERS[@]}"; do
  url="${BASE}/${ch}.html"
  printf '  %-24s ' "$ch"
  if ! curl -fsSL "$url" -o ".fetch/${ch}.html"; then
    echo "FAILED"
    echo
    echo "Could not fetch ${url}"
    echo "Chapter slugs change between manual versions. Check the index at ${BASE}/"
    exit 1
  fi
  echo "ok"
done

{
  echo "<!-- SUBSTRATE"
  echo "source: ${BASE}/"
  echo "chapters: ${CHAPTERS[*]}"
  echo "fetched: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "license: Apache License 2.0 (Apache Software Foundation)"
  echo "note: fetched verbatim, not authored. Do not edit this file."
  echo "-->"
  echo

  for ch in "${CHAPTERS[@]}"; do
    echo
    echo "<!-- chapter: ${ch} | ${BASE}/${ch}.html -->"
    echo
    pandoc -f html -t markdown_strict --wrap=none ".fetch/${ch}.html"
    echo
  done
} > design.md

rm -rf .fetch

# Strip pandoc anchor cruft and normalise line endings. Content unchanged.
sed -i 's|<a href="#[^"]*" class="headerlink"[^>]*>[^<]*</a>||g' design.md
tr -d '\r' < design.md > design.tmp && mv design.tmp design.md

echo
echo "words:  $(wc -w < design.md)"
echo "sha256:"
shasum -a 256 design.md 2>/dev/null || sha256sum design.md

echo
echo "Publish the sha256 with your results so the run is reproducible."
echo "Now read design.md and fill truth/elements.md BY HAND, before opening any prompt."
